### ISSUE TITLE
Document latest calculations in README

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/Pedersen-2023-DFC#1]
Describe sub-directories for injection effect and bLS uncertainty.

**Comment by sashahafner** [comment]
Did I do this yet? Better check.

**Comment by JohannaPedersen** [comment]
I'll wait with making a new release (and new doi for the resubmission of the paper) until you had a look at this.

**Comment by sashahafner** [comment]
OK. 
Will try to sort out today.

**Comment by sashahafner** [comment]
Done
